const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const Bet = require('../models/Bet');

const bets = [
  {
    date: '2025-08-23T10:00:00Z',
    sport: 'College Football',
    event: 'Miami FL ACC Regular Season Wins 2025-26',
    betType: 'Over/Under',
    odds: '+120',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Season win total for Miami FL',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-23T09:00:00Z',
    sport: 'College Football',
    event: 'Miami Florida To Make the Playoffs 2025-26',
    betType: 'Prop Bet',
    odds: '-250',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Miami Florida to make the playoffs',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-23T12:00:00Z',
    sport: 'College Football',
    event: 'Iowa State (#21) @ Kansas State (#20)',
    betType: 'Point Spread',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Iowa State +3.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T12:00:00Z',
    sport: 'College Football',
    event: 'Texas (#1) @ Ohio State (#2)',
    betType: 'Point Spread',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Ohio State -2.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T14:30:00Z',
    sport: 'College Football',
    event: 'Old Dominion @ Indiana (#19)',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Indiana -23.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T15:30:00Z',
    sport: 'College Football',
    event: 'Alabama (#8) @ Florida State',
    betType: 'Over/Under',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Over 50.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T15:30:00Z',
    sport: 'College Football',
    event: 'Nevada @ Penn State (#3)',
    betType: 'Point Spread',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Penn State -44.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T19:30:00Z',
    sport: 'College Football',
    event: 'LSU (#9) @ Clemson (#6)',
    betType: 'Over/Under',
    odds: '-105',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Under 57',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-31T15:00:00Z',
    sport: 'College Football',
    event: 'Virginia Tech @ South Carolina (#13)',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Virginia Tech +8.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-31T19:30:00Z',
    sport: 'College Football',
    event: 'Notre Dame (#5) @ Miami Florida (#10)',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Notre Dame -2.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-09-04T18:00:00Z',
    sport: 'NFL Football',
    event: 'Washington Commanders To Make the Playoffs 2025-26',
    betType: 'Prop Bet',
    odds: '+115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Washington Commanders to make the playoffs',
    note: 'Seeded bet',
  },
  {
    date: '2025-09-04T20:00:00Z',
    sport: 'NFL Football',
    event: 'NFC East Winner 2025-26',
    betType: 'Prop Bet',
    odds: '+600',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Dallas Cowboys to win NFC East',
    note: 'Seeded bet',
  },
  {
    date: '2025-09-07T13:00:00Z',
    sport: 'NFL Football',
    event: '49ers Regular Season Wins 2025-26',
    betType: 'Over/Under',
    odds: '-120',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: '49ers regular season win total',
    note: 'Seeded bet',
  },
];

async function insertBets() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    const result = await Bet.insertMany(bets);
    console.log(`${result.length} bets inserted`);
  } catch (err) {
    console.error(err);
  } finally {
    await mongoose.disconnect();
  }
}

insertBets();