import mongoose from 'mongoose';
import bcrypt from 'bcrypt';
import connectDB from '../src/db.js';
import User from '../src/models/User.js';
import Bet from '../src/models/Bet.js';

const username = 'nowbenj';
const password = 'Betting24$';

const bets = [
  {
    date: '2025-08-23T10:00:00Z',
    sport: 'College Football',
    event: 'Miami FL ACC Regular Season Wins 2025-26',
    betType: 'Over/Under',
    odds: '+120',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Season win total for Miami FL',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-23T09:00:00Z',
    sport: 'College Football',
    event: 'Miami Florida To Make the Playoffs 2025-26',
    betType: 'Prop Bet',
    odds: '-250',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Miami Florida to make the playoffs',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-23T12:00:00Z',
    sport: 'College Football',
    event: 'Iowa State (#21) @ Kansas State (#20)',
    betType: 'Point Spread',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Iowa State +3.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T12:00:00Z',
    sport: 'College Football',
    event: 'Texas (#1) @ Ohio State (#2)',
    betType: 'Point Spread',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Ohio State -2.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T14:30:00Z',
    sport: 'College Football',
    event: 'Old Dominion @ Indiana (#19)',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Indiana -23.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T15:30:00Z',
    sport: 'College Football',
    event: 'Alabama (#8) @ Florida State',
    betType: 'Over/Under',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Over 50.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T15:30:00Z',
    sport: 'College Football',
    event: 'Nevada @ Penn State (#3)',
    betType: 'Point Spread',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Penn State -44.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-30T19:30:00Z',
    sport: 'College Football',
    event: 'LSU (#9) @ Clemson (#6)',
    betType: 'Over/Under',
    odds: '-105',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Under 57',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-31T15:00:00Z',
    sport: 'College Football',
    event: 'Virginia Tech @ South Carolina (#13)',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Virginia Tech +8.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-08-31T19:30:00Z',
    sport: 'College Football',
    event: 'Notre Dame (#5) @ Miami Florida (#10)',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Notre Dame -2.5',
    note: 'Seeded bet',
  },
  {
    date: '2025-09-04T18:00:00Z',
    sport: 'NFL Football',
    event: 'Washington Commanders To Make the Playoffs 2025-26',
    betType: 'Prop Bet',
    odds: '+115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Washington Commanders to make the playoffs',
    note: 'Seeded bet',
  },
  {
    date: '2025-09-04T20:00:00Z',
    sport: 'NFL Football',
    event: 'NFC East Winner 2025-26',
    betType: 'Prop Bet',
    odds: '+600',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Dallas Cowboys to win NFC East',
    note: 'Seeded bet',
  },
  {
    date: '2025-09-07T13:00:00Z',
    sport: 'NFL Football',
    event: '49ers Regular Season Wins 2025-26',
    betType: 'Over/Under',
    odds: '-120',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: '49ers regular season win total',
    note: 'Seeded bet',
  },
  {
    date: '2025-09-04T17:20:00Z',
    sport: 'NFL Football',
    event: 'Dallas Cowboys @ Philadelphia Eagles',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Dallas Cowboys +7.0',
    note: '',
  },
  {
    date: '2025-09-04T17:20:00Z',
    sport: 'NFL Football',
    event: 'Dallas Cowboys @ Philadelphia Eagles',
    betType: 'Over/Under',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Over 44.5',
    note: '',
  },
  {
    date: '2025-09-05T17:00:00Z',
    sport: 'NFL Football',
    event: 'Kansas City Chiefs @ Los Angeles Chargers',
    betType: 'Over/Under',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Under 43',
    note: '',
  },
  {
    date: '2025-09-07T10:00:00Z',
    sport: 'NFL Football',
    event: 'Las Vegas Raiders @ New England Patriots',
    betType: 'Point Spread',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'New York Giants +6.5',
    note: '',
  },
  {
    date: '2025-09-07T10:00:00Z',
    sport: 'NFL Football',
    event: 'Carolina Panthers @ Jacksonville Jaguars',
    betType: 'Point Spread',
    odds: '+100',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Carolina Panthers +2.5',
    note: '',
  },
  {
    date: '2025-09-07T10:00:00Z',
    sport: 'NFL Football',
    event: 'Tampa Bay Buccaneers @ Atlanta Falcons',
    betType: 'Over/Under',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Over 48.5',
    note: '',
  },
  {
    date: '2025-09-07T13:05:00Z',
    sport: 'NFL Football',
    event: 'Tennessee Titans @ Denver Broncos',
    betType: 'Point Spread',
    odds: '-105',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Tennessee Titans +7.5',
    note: '',
  },
  {
    date: '2025-09-07T13:05:00Z',
    sport: 'NFL Football',
    event: 'San Francisco 49ers @ Seattle Seahawks',
    betType: 'Over/Under',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Under 45',
    note: '',
  },
  {
    date: '2025-09-07T13:25:00Z',
    sport: 'NFL Football',
    event: 'Houston Texans @ Los Angeles Rams',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Los Angeles Rams -2.5',
    note: '',
  },
  {
    date: '2025-09-07T13:25:00Z',
    sport: 'NFL Football',
    event: 'Detroit Lions @ Green Bay Packers',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Detroit Lions +1.5',
    note: '',
  },
  {
    date: '2025-09-07T17:20:00Z',
    sport: 'NFL Football',
    event: 'Baltimore Ravens @ Buffalo Bills',
    betType: 'Point Spread',
    odds: '-110',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Baltimore Ravens +1.5',
    note: '',
  },
  {
    date: '2025-09-08T17:15:00Z',
    sport: 'NFL Football',
    event: 'Minnesota Vikings @ Chicago Bears',
    betType: 'Point Spread',
    odds: '-115',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Minnesota Vikings -2.0',
    note: '',
  },
  {
    date: '2025-09-04T21:00:00Z',
    sport: 'NFL Football',
    event: 'Offensive Rookie of the Year 2025-26',
    betType: 'Futures',
    odds: '+340',
    stake: 110,
    outcome: 'Pending',
    payout: 0,
    profitLoss: 0,
    description: 'Cameron Ward (TEN)',
    note: '',
  },
];

(async () => {
  try {
    await connectDB();
    let user = await User.findOne({ username });
    if (!user) {
      const hashedPassword = await bcrypt.hash(password, 10);
      user = await User.create({ username, password: hashedPassword });
      console.log(`Created user ${username}`);
    } else {
      console.log(`User ${username} already exists`);
    }

    const betsWithUser = bets.map(bet => ({ ...bet, user: user._id }));
    const result = await Bet.insertMany(betsWithUser);
    console.log(`Inserted ${result.length} bets for ${username}`);
  } catch (err) {
    console.error(err);
  } finally {
    await mongoose.disconnect();
  }
})();

